Create Containerfile.operator files in preparation to move to RHTAP
open-cluster-management/thanos pull request #102
Opened 2024-05-04 02:21 UTC by subbarao-meduri

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

## Verification

2024-05-06 14:43 UTC, douglascamata requested changes

2024-05-06 14:43 UTC, douglascamata commented on Makefile.rhtap
@subbarao-meduri how will we maintain this Makefile? What do we have to do when it diverges from upstream? Can we **not** duplicate everything but only extend the make targets that we need?

2024-05-08 09:25 UTC, douglascamata approved these changes
/lgtm

2024-05-08 11:38 UTC, subbarao-meduri commented on Makefile.rhtap
@douglascamata I re-did the new Makefile targets to only override specific targets while including original Makefile. This should make it easier to maintain. Please review.

2024-05-08 19:17 UTC, merged